apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api-dp
  namespace: storage-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway-api
  template:
    metadata:
      name: gateway-api-pod
      labels:
        app: gateway-api
    spec:
      containers:
      - name: gateway-api
        image: cdjhonata/gateway-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
