apiVersion: v1
kind: Service
metadata:
  name: storage-db-svc
  namespace: storage-ns
spec: 
  type: ClusterIP
  selector:
    app: storage-db
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
